(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   '("7447f4f58bf7719c58a2b945493f2308e15079950fa251cc4dbb48adf70d8198" default))
 '(magit-todos-insert-after '(bottom) nil nil "Changed by setter of obsolete option `magit-todos-insert-at'")
 '(tree-sitter-major-mode-language-alist
   '((agda2-mode . agda)
     (sh-mode . bash)
     (c-mode . c)
     (caml-mode . ocaml)
     (clojure-mode . clojure)
     (csharp-mode . c-sharp)
     (c++-mode . cpp)
     (d-mode . d)
     (css-mode . css)
     (elm-mode . elm)
     (elixir-mode . elixir)
     (erlang-mode . erlang)
     (ess-r-mode . r)
     (fennel-mode . fennel)
     (go-mode . go)
     (haskell-mode . haskell)
     (hcl-mode . hcl)
     (terraform-mode . hcl)
     (html-mode . html)
     (markdown-mode . markdown)
     (mhtml-mode . html)
     (nix-mode . nix)
     (java-mode . java)
     (javascript-mode . javascript)
     (js-mode . javascript)
     (js2-mode . javascript)
     (js3-mode . javascript)
     (json-mode . json)
     (jsonc-mode . json)
     (julia-mode . julia)
     (lua-mode . lua)
     (meson-mode . meson)
     (ocaml-mode . ocaml)
     (perl-mode . perl)
     (php-mode . php)
     (prisma-mode . prisma)
     (python-mode . python)
     (pygn-mode . pgn)
     (rjsx-mode . javascript)
     (ruby-mode . ruby)
     (rust-mode . rust)
     (rustic-mode . rust)
     (scala-mode . scala)
     (scheme-mode . scheme)
     (swift-mode . swift)
     (toml-mode . toml)
     (tuareg-mode . ocaml)
     (typescript-mode . tsx)
     (verilog-mode . verilog)
     (yaml-mode . yaml)
     (zig-mode . zig))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
